
backend:
  name: github
  repo: 0rch1dL4bs/tokoroti
  branch: main
  base_url: https://azizah-oauth.kakakuku8963.workers.dev
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "katalog"
    label: "Manajemen Katalog"
    files:
      - label: "Daftar Roti"
        name: "products"
        file: "data/products.json"
        fields:
          - label: "Daftar Produk"
            name: "products"
            widget: "list"
            fields:
              - label: "ID Roti (Angka Unik)"
                name: "id"
                widget: "number"
              - label: "Nama Roti"
                name: "name"
                widget: "string"
              - label: "Harga (Rupiah)"
                name: "price"
                widget: "number"
              - label: "Gambar"
                name: "img"
                widget: "image"
              - label: "Deskripsi Singkat"
                name: "desc"
                widget: "text"
              - label: "Status: Ready Hari Ini?"
                name: "isReadyToday"
                widget: "boolean"
                default: true